name: DBJ Docker Build

on:   
  watch:
    types: [started]
#   repository_dispatch:
#     types: [DBJ_Update_Action]

jobs:
  build_job:
    name: DBJ Docker Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Private Actions Checkout
        uses: actions/checkout@v2.3.4
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0
#       - 
#         name: Create local changes
#         run: |
#           wget -O README.md `curl -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.TOKEN_GITHUB }} -s 'https://api.github.com/repos/wgpsec/DBJ/contents/README.md' | grep "download_url" | cut -d '"' -f 4`
#           sed -i '3 a [![Docker Automated Build](https://img.shields.io/docker/automated/${{ secrets.DOCKERHUB_USERNAME }}/dbj?label=Build&logo=docker&style=flat-square)](https://hub.docker.com/r/${{ secrets.DOCKERHUB_USERNAME }}/dbj) [![CobaltStrike Docker Build](https://github.com/${{ secrets.DOCKERHUB_USERNAME }}/DBJ/actions/workflows/Dbj_Docker_Build.yml/badge.svg)](https://github.com/${{ secrets.DOCKERHUB_USERNAME }}/DBJ/actions/workflows/Dbj_Docker_Build.yml)' README.md
#       - 
#         name: Commit files
#         run: |
#           git config --local user.email "github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git add README.md
#           git commit -m "Add changes by DBJ_Update_Action" -a
      -
        name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dbj:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dbj:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/dbj:cache,mode=max
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/dbj
